version: 0.0
os: linux
files:
  - source: index.html  # Correct source path (no leading slash)
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies  # Ensure this script exists
      timeout: 300
      runas: root
    - location: scripts/start_server  # Ensure this script exists and can start your server (e.g., Apache or Nginx)
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server  # Ensure this script exists and can stop the server
      timeout: 300
      runas: root
